# SPDX-License-Identifier: MIT
# Copyright (C) 2026 mg6630

name: SUPERGATEWAY-S20P-NO-WIFI
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
permissions: write-all
jobs:
  build:
    name: SuperGateway S20P (No WiFi)
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: SUPERGATEWAY-S20P-NO-WIFI
      WRT_THEME: aurora
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.1.254
      WRT_PW: password
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: owrt
      WRT_SOURCE: VIKINGYFY/immortalwrt